inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
AllCops:
  Exclude:
    - db/**
    - vendor/**/*
    - spec/support/share_db_connection.rb
Rails:
  Enabled: true
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb
    - app/models/todo_list.rb
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'
Style/GuardClause:
  Enabled: false
