inherit_from: .rubocop_todo.yml
Documentation:
  Enabled: false
AllCops:
  Exclude:
    - db/**
    - vendor/**/*
Rails:
  Enabled: true
Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'
Style/GuardClause:
  Enabled: false
