scss_files: 'app/assets/stylesheets'

linters:
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  IdSelector:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    order: smacss
  SelectorDepth:
    max_depth: 4
  SelectorFormat:
    ignored_names: ['field_with_errors']
  VendorPrefix:
    enabled: false
